# Generated by Django 2.1.7 on 2019-03-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_secret', '0001_initial'),
        ('file_handler', '0002_auto_20190210_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_secret.ShamirSS'),
        ),
    ]
