# Generated by Django 2.1.7 on 2019-03-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0002_auto_20190210_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
