version: '3.9'
services:
  db:
    image: postgres:latest

  nginx:
    image: nginx:1.13-alpine
    container_name: nginx01
    ports:
      - "8000:8000"
    volumes:
      - ../:/src
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    environment:
      - DJANGO_CONFIGURATION=Dev
      - DJANGO_SETTINGS_MODULE=my_cloud.settings
    build: .
    container_name: django01
    privileged: true
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --reload my_cloud.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ../:/src
    expose:
      - "8000"
    restart: always
