# Generated by Django 2.1.7 on 2019-03-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_secret', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shamirss',
            name='mers_exp',
            field=models.IntegerField(choices=[(89, '89'), (107, '107'), (127, '127')]),
        ),
    ]
