# Generated by Django 2.1.7 on 2019-03-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_secret', '0002_auto_20190305_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='shamirss',
            name='secret',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
    ]
