# Generated by Django 2.1.7 on 2019-03-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_secret', '0003_shamirss_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shamirss',
            name='secret',
            field=models.CharField(default='none', max_length=128),
        ),
    ]
