# Generated by Django 2.1.7 on 2019-03-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_secret', '0004_auto_20190307_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shamirss',
            name='secret',
            field=models.CharField(max_length=128),
        ),
    ]
