# Generated by Django 5.2.17 on 2026-09-19 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_secret', '0005_auto_20190307_1211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shamirss',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
